development:
  session_key: examplo_desenvolvimento
  session_secret: exemplo_desenvolvimento
  domain: http://debateaberto.dev
  facebook_app_id: exemplo_app_id
  facebook_app_secret: exemplo_app_secret
  server: http://debateaberto.dev/faye
  secret_token: exemplo
  signature_expiration: 3600 # uma hora

test:
  session_key: examplo_teste
  session_secret: exemplo_teste
  domain: http://debateaberto.dev
  facebook_app_id: exemplo_app_id
  facebook_app_secret: exemplo_app_secret
  server: http://debateaberto.dev/faye
  secret_token: exemplo
  signature_expiration: 3600 # uma hora

production:
  session_key: examplo_producao
  session_secret: exemplo_producao
  domain: http://debateaberto.org
  facebook_app_id: exemplo_app_id
  facebook_app_secret: exemplo_app_secret
  server: http://debateaberto.org/faye
  secret_token: exemplo
  signature_expiration: 3600 # uma hora
